#!/usr/bin/env bash
# This script prints a lot of things on different iterations

i=0
while [ $i -lt 10 ]
do
if [ $i = 4 ]
then
echo "bad luck"
elif [ $i = 8 ]
then
echo "good luck"
else
echo "Holberton School"
fi
done
